version: "3"
services:
  project:
    image: mos4d
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ipc: host
    network_mode: host
    volumes:
      - ${PWD}/:/mos4d
      - ${DATA}:/mos4d/data
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_MASTER_URI=$ROS_MASTER_URI