EXPERIMENT:
  ID: SPS # Long-Term Object Segmentation OR 5DMOS

##Data
DATA:
  SHUFFLE: True
  RADIUS: 50
  NUM_WORKER: 4
  SPLIT:
    TRAIN:
      - '20220420'
      - '20220601'
    VAL:
      - '20220608'
    TEST:
      - '20220629'
      - '20220714'

##Training
TRAIN:
  MAP: april_6_ABEF.asc
  MAX_EPOCH: 60
  LR: 0.00007
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 1
  AUGMENTATION: True

LOGGER:
  NEPTUNE:
    API_KEY: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJhNGY5M2M3OC0yNGVmLTQyYmItYWFkZi0xYTVmMjk4ODYxYjUifQ=="  # replace with your own
    PROJECT: "ihroob/SPS"  # format "workspace-name/project-name"

##Network
MODEL:
  VOXEL_SIZE: 0.1 # Used for discretization in x,y,z when creating a sparse tensor 

