EXPERIMENT:
  ID: SPS_ME_BinaryCrossEntroby # Long-Term Object Segmentation OR 5DMOS

##Data
DATA:
  SHUFFLE: True
  NUM_WORKER: 8
  ME_PRUNE: False
  SPLIT:
    TRAIN:
      - '20220420'
      - '20220601'
    VAL:
      - '20220608'
    TEST:
      - '20220629'
      - '20220714'

##Training
TRAIN:
  MAP: base_map.asc.npy
  MAX_EPOCH: 80
  LR: 0.00007
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 4
  AUGMENTATION: True

##Network
MODEL:
  VOXEL_SIZE: 0.1 # Used for discretization in x,y,z when creating a sparse tensor 